### ISSUE TITLE
any plan to support react-fiber

### ISSUE THREAD

**Issue by cometta** [grommet/react-desc#1]
any plan to support react-fiber

**Comment by alansouzati** [comment]
Yeah, eventually we will look into this. Right now, fiber (React 16) is not officially released yet. From what I understand Fiber will be an internal change that will be mostly backwards compatible.

PropTypes is now a separate repo, and I believe this project will not be affect by the fiber release. Do you have anything in mind that we need to address before it is officially released?

**Comment by adamroldfield** [comment]
This package triggers:

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by alansouzati** [comment]
yeah. let me work on updating this.

**Comment by alansouzati** [comment]
Actually support for the new proptypes was already added [here](https://github.com/grommet/react-desc/commit/bf69c63605bbbdf7d1a261535a54e93758d0263a)

It should be part of version 1.1.0. Is this the version you are using @adamroldfield ?

**Comment by alansouzati** [comment]
I'm closing this issue since I believe there is nothing to be changed for react-desc
