### ISSUE TITLE
Release react-desc

### ISSUE THREAD

**Issue by thomasmatecki** [grommet/react-desc#23]
`create-react-app` now defaults to react `17.0.1` which isn't supported by [4.1.2](https://github.com/grommet/react-desc/compare/v4.1.2...master). This results in a conflict when following the instructions [here](https://github.com/grommet/grommet-starter-new-app).

**Comment by ShimiSun** [comment]
Thanks for reporting, v4.1.3 is now available on NPM https://github.com/grommet/react-desc/releases/tag/v4.1.3
